name       : jags
version    : 4.3.0
release    : 2
source     :
    - https://nchc.dl.sourceforge.net/project/mcmc-jags/JAGS/4.x/Source/JAGS-4.3.0.tar.gz : 8ac5dd57982bfd7d5f0ee384499d62f3e0bb35b5f1660feb368545f1186371fc
license    : GPL-2.0
component  : office.scientific
summary    : JAGS is Just Another Gibbs Sampler.  It is a program for analysis of Bayesian hierarchical models using Markov Chain Monte Carlo (MCMC) simulation  not wholly unlike BUGS.
description: |
    JAGS is Just Another Gibbs Sampler.  It is a program for analysis of Bayesian hierarchical models using Markov Chain Monte Carlo (MCMC) simulation  not wholly unlike BUGS.
builddeps  :
    - pkgconfig(cppunit)
    - openblas-devel
setup      : |
    %configure --with-blas=openblas --with-lapack=openblas
build      : |
    %make
install    : |
    %make_install
